# Generated by Django 4.2.7 on 2023-11-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='designrequest',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='designrequest',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='designrequest',
            name='title',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
