# Generated by Django 4.2.7 on 2023-11-17 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_designrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designrequest',
            name='category',
            field=models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='catalog.designcategory', verbose_name='designrequest category'),
        ),
    ]
