# Generated by Django 4.2.7 on 2023-11-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_designrequest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='photo',
            field=models.ImageField(default='no-photo.jpg', upload_to='design_photos/'),
        ),
    ]
