# Generated by Django 4.2.7 on 2023-11-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_designrequest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designrequest',
            name='photo',
            field=models.ImageField(default='no-photo.jpg', null=True, upload_to='design_photos/'),
        ),
    ]
