# Generated by Django 4.2.7 on 2023-11-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_designrequest_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designrequest',
            name='image',
        ),
    ]
