# Generated by Django 4.2.7 on 2023-11-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_designrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designrequest',
            name='comment',
        ),
    ]
